/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.chat.model.implementation;

/**
 * Basic interface for {@link #CHAT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ChatBase extends com.top_logic.model.TLObject {

	/**
	 * Name of type <code>Chat</code>
	 */
	String CHAT_TYPE = "Chat";

	/**
	 * Part <code>chatId</code> of <code>Chat</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String CHAT_ID_ATTR = "chatId";

	/**
	 * Part <code>createdAt</code> of <code>Chat</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:DateTime</code> in configuration.
	 * </p>
	 */
	String CREATED_AT_ATTR = "createdAt";

	/**
	 * Part <code>lastMessageAt</code> of <code>Chat</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:DateTime</code> in configuration.
	 * </p>
	 */
	String LAST_MESSAGE_AT_ATTR = "lastMessageAt";

	/**
	 * Part <code>messages</code> of <code>Chat</code>
	 * 
	 * <p>
	 * Declared as <code>tl.chat:ChatMessage</code> in configuration.
	 * </p>
	 */
	String MESSAGES_ATTR = "messages";

	/**
	 * Getter for part {@link #CHAT_ID_ATTR}.
	 */
	default String getChatId() {
		return (String) tValueByName(CHAT_ID_ATTR);
	}

	/**
	 * Setter for part {@link #CHAT_ID_ATTR}.
	 */
	default void setChatId(String newValue) {
		tUpdateByName(CHAT_ID_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #CREATED_AT_ATTR}.
	 */
	default java.util.Date getCreatedAt() {
		return (java.util.Date) tValueByName(CREATED_AT_ATTR);
	}

	/**
	 * Setter for part {@link #CREATED_AT_ATTR}.
	 */
	default void setCreatedAt(java.util.Date newValue) {
		tUpdateByName(CREATED_AT_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #LAST_MESSAGE_AT_ATTR}.
	 */
	default java.util.Date getLastMessageAt() {
		return (java.util.Date) tValueByName(LAST_MESSAGE_AT_ATTR);
	}

	/**
	 * Setter for part {@link #LAST_MESSAGE_AT_ATTR}.
	 */
	default void setLastMessageAt(java.util.Date newValue) {
		tUpdateByName(LAST_MESSAGE_AT_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #MESSAGES_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.List<? extends com.top_logic.chat.model.interfaces.ChatMessage> getMessages() {
		return (java.util.List<? extends com.top_logic.chat.model.interfaces.ChatMessage>) tValueByName(MESSAGES_ATTR);
	}

	/**
	 * Live view of the {@link #MESSAGES_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.List<com.top_logic.chat.model.interfaces.ChatMessage> getMessagesModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(MESSAGES_ATTR);
		@SuppressWarnings("unchecked")
		java.util.List<com.top_logic.chat.model.interfaces.ChatMessage> result = (java.util.List<com.top_logic.chat.model.interfaces.ChatMessage>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #MESSAGES_ATTR}.
	 */
	default void setMessages(java.util.List<com.top_logic.chat.model.interfaces.ChatMessage> newValue) {
		tUpdateByName(MESSAGES_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #MESSAGES_ATTR} reference.
	 */
	default void addMessage(com.top_logic.chat.model.interfaces.ChatMessage newValue) {
		tAddByName(MESSAGES_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #MESSAGES_ATTR} reference.
	 */
	default void removeMessage(com.top_logic.chat.model.interfaces.ChatMessage oldValue) {
		tRemoveByName(MESSAGES_ATTR, oldValue);
	}

}
