/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.chat.model.implementation;

import com.top_logic.knowledge.objects.KnowledgeObject;

/**
 * Wrapper implementation class for <code>tl.chat:ChatMessage</code> business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.ImplementationTemplateGenerator}
 */
public class ChatMessageImpl extends com.top_logic.element.structured.wrap.AttributedStructuredElementWrapper implements com.top_logic.chat.model.interfaces.ChatMessage {

	/**
	 * Default constructor.
	 */
	public ChatMessageImpl(KnowledgeObject ko) {
		super(ko);
	}

}
