/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.chat.model.implementation;

/**
 * Basic interface for {@link #CHAT_ROOT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ChatRootBase extends com.top_logic.model.TLObject {

	/**
	 * Name of type <code>ChatRoot</code>
	 */
	String CHAT_ROOT_TYPE = "ChatRoot";

	/**
	 * Part <code>chats</code> of <code>ChatRoot</code>
	 * 
	 * <p>
	 * Declared as <code>tl.chat:Chat</code> in configuration.
	 * </p>
	 */
	String CHATS_ATTR = "chats";

	/**
	 * Getter for part {@link #CHATS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.List<? extends com.top_logic.chat.model.interfaces.Chat> getChats() {
		return (java.util.List<? extends com.top_logic.chat.model.interfaces.Chat>) tValueByName(CHATS_ATTR);
	}

	/**
	 * Live view of the {@link #CHATS_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.List<com.top_logic.chat.model.interfaces.Chat> getChatsModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(CHATS_ATTR);
		@SuppressWarnings("unchecked")
		java.util.List<com.top_logic.chat.model.interfaces.Chat> result = (java.util.List<com.top_logic.chat.model.interfaces.Chat>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #CHATS_ATTR}.
	 */
	default void setChats(java.util.List<com.top_logic.chat.model.interfaces.Chat> newValue) {
		tUpdateByName(CHATS_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #CHATS_ATTR} reference.
	 */
	default void addChat(com.top_logic.chat.model.interfaces.Chat newValue) {
		tAddByName(CHATS_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #CHATS_ATTR} reference.
	 */
	default void removeChat(com.top_logic.chat.model.interfaces.Chat oldValue) {
		tRemoveByName(CHATS_ATTR, oldValue);
	}

}
