/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.chat.model.implementation;

/**
 * Basic interface for {@link #CHAT_MESSAGE_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ChatMessageBase extends com.top_logic.model.TLObject {

	/**
	 * Name of type <code>ChatMessage</code>
	 */
	String CHAT_MESSAGE_TYPE = "ChatMessage";

	/**
	 * Part <code>chat</code> of <code>ChatMessage</code>
	 * 
	 * <p>
	 * Declared as <code>tl.chat:Chat</code> in configuration.
	 * </p>
	 */
	String CHAT_ATTR = "chat";

	/**
	 * Part <code>role</code> of <code>ChatMessage</code>
	 * 
	 * <p>
	 * Declared as <code>tl.accounts:Person</code> in configuration.
	 * </p>
	 */
	String ROLE_ATTR = "role";

	/**
	 * Part <code>text</code> of <code>ChatMessage</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Text</code> in configuration.
	 * </p>
	 */
	String TEXT_ATTR = "text";

	/**
	 * Part <code>timestamp</code> of <code>ChatMessage</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:DateTime</code> in configuration.
	 * </p>
	 */
	String TIMESTAMP_ATTR = "timestamp";

	/**
	 * Getter for part {@link #CHAT_ATTR}.
	 */
	default com.top_logic.chat.model.interfaces.Chat getChat() {
		return (com.top_logic.chat.model.interfaces.Chat) tValueByName(CHAT_ATTR);
	}

	/**
	 * Getter for part {@link #ROLE_ATTR}.
	 */
	default com.top_logic.knowledge.wrap.person.Person getRole() {
		return (com.top_logic.knowledge.wrap.person.Person) tValueByName(ROLE_ATTR);
	}

	/**
	 * Setter for part {@link #ROLE_ATTR}.
	 */
	default void setRole(com.top_logic.knowledge.wrap.person.Person newValue) {
		tUpdateByName(ROLE_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #TEXT_ATTR}.
	 */
	default String getText() {
		return (String) tValueByName(TEXT_ATTR);
	}

	/**
	 * Setter for part {@link #TEXT_ATTR}.
	 */
	default void setText(String newValue) {
		tUpdateByName(TEXT_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #TIMESTAMP_ATTR}.
	 */
	default java.util.Date getTimestamp() {
		return (java.util.Date) tValueByName(TIMESTAMP_ATTR);
	}

	/**
	 * Setter for part {@link #TIMESTAMP_ATTR}.
	 */
	default void setTimestamp(java.util.Date newValue) {
		tUpdateByName(TIMESTAMP_ATTR, newValue);
	}

}
