/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.chat.model.interfaces;

/**
 * Factory for <code>tl.chat</code> objects.
 * 
 * <p>
 * Note: this is generated code. Do not modify. Instead, create a subclass and register this in the module system.
 * </p>
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.FactoryGenerator}
 */
public class TlChatFactory extends com.top_logic.element.structured.wrap.StructuredElementWrapperFactory {

	/**
	 * Name of singleton {@link #TL_CHAT_STRUCTURE}.
	 */
	public static final String SINGLETON_CHATROOT = "ChatRoot";

	/**
	 * Name of the structure <code>tl.chat</code> defined by {@link TlChatFactory}.
	 */
	public static final String TL_CHAT_STRUCTURE = "tl.chat";

	/**
	 * Lookup {@link ChatRoot} type.
	 */
	public static com.top_logic.model.TLClass getChatRootType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_CHAT_STRUCTURE).getType(ChatRoot.CHAT_ROOT_TYPE);
	}

	/**
	 * Lookup {@link ChatRoot#CHATS_ATTR} of {@link ChatRoot}.
	 */
	public static com.top_logic.model.TLReference getChatsChatRootAttr() {
		return (com.top_logic.model.TLReference) getChatRootType().getPart(ChatRoot.CHATS_ATTR);
	}

	/**
	 * Lookup {@link Chat} type.
	 */
	public static com.top_logic.model.TLClass getChatType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_CHAT_STRUCTURE).getType(Chat.CHAT_TYPE);
	}

	/**
	 * Lookup {@link Chat#CHAT_ID_ATTR} of {@link Chat}.
	 */
	public static com.top_logic.model.TLProperty getChatIdChatAttr() {
		return (com.top_logic.model.TLProperty) getChatType().getPart(Chat.CHAT_ID_ATTR);
	}

	/**
	 * Lookup {@link Chat#CREATED_AT_ATTR} of {@link Chat}.
	 */
	public static com.top_logic.model.TLProperty getCreatedAtChatAttr() {
		return (com.top_logic.model.TLProperty) getChatType().getPart(Chat.CREATED_AT_ATTR);
	}

	/**
	 * Lookup {@link Chat#LAST_MESSAGE_AT_ATTR} of {@link Chat}.
	 */
	public static com.top_logic.model.TLProperty getLastMessageAtChatAttr() {
		return (com.top_logic.model.TLProperty) getChatType().getPart(Chat.LAST_MESSAGE_AT_ATTR);
	}

	/**
	 * Lookup {@link Chat#MESSAGES_ATTR} of {@link Chat}.
	 */
	public static com.top_logic.model.TLReference getMessagesChatAttr() {
		return (com.top_logic.model.TLReference) getChatType().getPart(Chat.MESSAGES_ATTR);
	}

	/**
	 * Lookup {@link ChatMessage} type.
	 */
	public static com.top_logic.model.TLClass getChatMessageType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_CHAT_STRUCTURE).getType(ChatMessage.CHAT_MESSAGE_TYPE);
	}

	/**
	 * Lookup {@link ChatMessage#CHAT_ATTR} of {@link ChatMessage}.
	 */
	public static com.top_logic.model.TLReference getChatChatMessageAttr() {
		return (com.top_logic.model.TLReference) getChatMessageType().getPart(ChatMessage.CHAT_ATTR);
	}

	/**
	 * Lookup {@link ChatMessage#ROLE_ATTR} of {@link ChatMessage}.
	 */
	public static com.top_logic.model.TLReference getRoleChatMessageAttr() {
		return (com.top_logic.model.TLReference) getChatMessageType().getPart(ChatMessage.ROLE_ATTR);
	}

	/**
	 * Lookup {@link ChatMessage#TEXT_ATTR} of {@link ChatMessage}.
	 */
	public static com.top_logic.model.TLProperty getTextChatMessageAttr() {
		return (com.top_logic.model.TLProperty) getChatMessageType().getPart(ChatMessage.TEXT_ATTR);
	}

	/**
	 * Lookup {@link ChatMessage#TIMESTAMP_ATTR} of {@link ChatMessage}.
	 */
	public static com.top_logic.model.TLProperty getTimestampChatMessageAttr() {
		return (com.top_logic.model.TLProperty) getChatMessageType().getPart(ChatMessage.TIMESTAMP_ATTR);
	}

	/**
	 * Name of type <code>ChatRoot</code> in structure {@link #TL_CHAT_STRUCTURE}.
	 * 
	 * @deprecated Use {@link ChatRoot#CHAT_ROOT_TYPE}.
	 */
	@Deprecated
	public static final String CHAT_ROOT_NODE = ChatRoot.CHAT_ROOT_TYPE;

	/**
	 * Storage table name of {@link #CHAT_ROOT_NODE} objects.
	 */
	public static final String KO_NAME_CHAT_ROOT = "GenericObject";

	/**
	 * Name of type <code>Chat</code> in structure {@link #TL_CHAT_STRUCTURE}.
	 * 
	 * @deprecated Use {@link Chat#CHAT_TYPE}.
	 */
	@Deprecated
	public static final String CHAT_NODE = Chat.CHAT_TYPE;

	/**
	 * Storage table name of {@link #CHAT_NODE} objects.
	 */
	public static final String KO_NAME_CHAT = "GenericObject";

	/**
	 * Name of type <code>ChatMessage</code> in structure {@link #TL_CHAT_STRUCTURE}.
	 * 
	 * @deprecated Use {@link ChatMessage#CHAT_MESSAGE_TYPE}.
	 */
	@Deprecated
	public static final String CHAT_MESSAGE_NODE = ChatMessage.CHAT_MESSAGE_TYPE;

	/**
	 * Storage table name of {@link #CHAT_MESSAGE_NODE} objects.
	 */
	public static final String KO_NAME_CHAT_MESSAGE = "GenericObject";

	/**
	 * Singleton <code>ChatRoot</code>.
	 */
	public ChatRoot getChatrootSingleton() {
		return (ChatRoot) lookupSingleton(SINGLETON_CHATROOT);
	}

	/**
	 * Singleton <code>ChatRoot</code> on given branch.
	 */
	public ChatRoot getChatrootSingleton(com.top_logic.knowledge.service.Branch requestedBranch) {
		return (ChatRoot) lookupSingleton(SINGLETON_CHATROOT, requestedBranch);
	}

	/**
	 * Singleton <code>ChatRoot</code> on given branch in given revision.
	 */
	public ChatRoot getChatrootSingleton(com.top_logic.knowledge.service.Branch requestedBranch, com.top_logic.knowledge.service.Revision historyContext) {
		return (ChatRoot) lookupSingleton(SINGLETON_CHATROOT, requestedBranch, historyContext);
	}


	/**
	 * Create an instance of {@link ChatRoot} type.
	 */
	public final ChatRoot createChatRoot(com.top_logic.model.TLObject context) {
		return (ChatRoot) createObject(getChatRootType(), context);
	}

	/**
	 * Create an instance of {@link ChatRoot} type.
	 */
	public final ChatRoot createChatRoot() {
		return createChatRoot(null);
	}

	/**
	 * Create an instance of {@link Chat} type.
	 */
	public final Chat createChat(com.top_logic.model.TLObject context) {
		return (Chat) createObject(getChatType(), context);
	}

	/**
	 * Create an instance of {@link Chat} type.
	 */
	public final Chat createChat() {
		return createChat(null);
	}

	/**
	 * Create an instance of {@link ChatMessage} type.
	 */
	public final ChatMessage createChatMessage(com.top_logic.model.TLObject context) {
		return (ChatMessage) createObject(getChatMessageType(), context);
	}

	/**
	 * Create an instance of {@link ChatMessage} type.
	 */
	public final ChatMessage createChatMessage() {
		return createChatMessage(null);
	}

	/**
	 * The singleton instance of {@link TlChatFactory}.
	 */
	public static TlChatFactory getInstance() {
		return (TlChatFactory) com.top_logic.element.model.DynamicModelService.getFactoryFor(TL_CHAT_STRUCTURE);
	}
}
